server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: nacos:gateway.yaml
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
  cloud:
    nacos:
      discovery:
        ephemeral: true
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有 actuator 端点，也可以指定 ["health", "info"]
  endpoint:
    health:
      show-details: always  # 显示详细健康信息
#      rabbit:
#          enabled: false
  server:
    port: 8002  # actuator 独立端口（可选，默认与主应用同端口）

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG