server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: nacos:jwt_config.yaml
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
  cloud:
    nacos:
      discovery:
        ephemeral: true
        server-addr: 192.168.118.1:8848
        ip: 192.168.118.1
      config:
        server-addr: 192.168.118.1:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        extension-configs:
          - data-id: jwt_config.yaml
            group: DEFAULT_GROUP
            refresh: true  # 动态刷新配置
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有 actuator 端点，也可以指定 ["health", "info"]
  endpoint:
    health:
      show-details: always  # 显示详细健康信息
#      rabbit:
#          enabled: false
  server:
    port: 8002  # actuator 独立端口（可选，默认与主应用同端口）

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

seata:
  enabled: true
  service:
    vgroupMapping:
      my_tx_group: default
    grouplist:
      default: 192.168.118.1:8091
  tx-service-group: my_tx_group
  config:
    type: nacos
    nacos:
      server-addr: 192.168.118.1:8848
      group: SEATA_GROUP
      namespace: ""
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.118.1:8848
      namespace: ""
      group: SEATA_GROUP


minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: root123456
  secure: false  # 使用HTTP而非HTTPS
  bucket-name: imooc

