server:
  port: 6001


spring:
  application:
    name: company-service
  # 忘了这一个
  profiles:
    active: dev
  config:
    import: nacos:jwt_config.yaml
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        extension-configs:
          - data-id: jwt_config.yaml
            group: DEFAULT_GROUP
            refresh: true  # 动态刷新配置
      discovery:
        server-addr: localhost:8848
        enabled: true
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000


seata:
  enabled: true
  service:
    vgroupMapping:
      my_tx_group: default
    grouplist:
      default: 192.168.118.1:8091
  tx-service-group: my_tx_group
  config:
    type: nacos
    nacos:
      server-addr: 192.168.118.1:8848
      group: SEATA_GROUP
      namespace: ""
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.118.1:8848
      namespace: ""
      group: SEATA_GROUP


minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: root123456
  secure: false  # 使用HTTP而非HTTPS
  bucket-name: imooc



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl