server:
  port: ${port:3001}
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  application:
    name: work-service
  profiles:
    active: dev
  config:
    import: nacos:gateway.yml
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
      discovery:
        server-addr: localhost:8848
        enabled: true
    loadbalancer:
        nacos:
          enabled: true   # 开启基于nacos规则的负载均衡

seata:
  enabled: true
  service:
    vgroupMapping:
      my_tx_group: default
    grouplist:
      default: 192.168.118.1:8091
  tx-service-group: my_tx_group
  config:
    type: nacos
    nacos:
      server-addr: 192.168.118.1:8848
      group: SEATA_GROUP
      namespace: ""
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.118.1:8848
      namespace: ""
      group: SEATA_GROUP