server:
  port: 8111
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  application:
    name: auth-service
  profiles:
    active: dev
#  注意 config.import 以及cloud.nacos.config都需要配置在application.yml 否者会出现配置错误
#  必须定义 config。import 否则会出现错误，
# config.import 的值  nacos:jwt_config.yaml 必须和        extension-configs，data-id: jwt_config.yaml 值一致，否则会出错
  config:
    import: nacos:jwt_config.yaml
  cloud:
    nacos:
      config:
        server-addr: 192.168.118.1:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
        extension-configs:
          - data-id: jwt_config.yaml
            group: DEFAULT_GROUP
            refresh: true  # 动态刷新配置
        refresh-enabled: true
      discovery:
        server-addr: localhost:8848
        enabled: true
    openfeign:
      client:
        config:
          default:
              connect-timeout: 5000
              read-timeout: 5000



minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: root123456
  secure: false  # 使用HTTP而非HTTPS
  bucket-name: imooc

#logging:
#  level:
#    com.alibaba.nacos: DEBUG
#    org.springframework.cloud.client.discovery: DEBUG

seata:
  enabled: true
  service:
    vgroupMapping:
      my_tx_group: default
    grouplist:
      default: 192.168.118.1:8091
  tx-service-group: my_tx_group
  config:
    type: nacos
    nacos:
      server-addr: 192.168.118.1:8848
      group: SEATA_GROUP
      namespace: ""

  registry:
    type: nacos
    nacos:
      server-addr: 192.168.118.1:8848
      namespace: ""
      group: SEATA_GROUP
#
#jwt:
#  key: fk23r23r23r23232323232323232323232323232323232323