spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-hire-dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: EJfKKkNc2H.

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  rabbitmq:
    username: guest
    password: guest
    virtual-host: "/"
    host: localhost
    port: 5672
    publisher-confirm-type: correlated # 生产端可靠性需要加上的confirm 回调
    publisher-returns: true # 生产端开启return回调
