spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-hire-dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: EJfKKkNc2H.

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
