springdoc:
  api-docs:
    enabled: true  # 开启 API 文档
  swagger-ui:
    enabled: true  # 启用 Swagger UI
    path: /swagger-ui.html  # 自定义 Swagger UI 访问路径
  default-flat-param-object: true  # 解决 @RequestBody + @RequestParam 混用参数格式问题

knife4j:
  enable: true  # 启用 Knife4j 增强功能
  setting:
    language: zh-CN  # 语言（可选 zh-CN / en）

spring:
  application:
    name: auto-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interview?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 1234qwer
